### ISSUE TITLE
How can i use this in Ionic project

### ISSUE THREAD

**Issue by CodingApp** [kamiazya/ngx-face-api-js#13]
Here are the thing that i have followed by checking docs.

Step 1: Installing package using npm i ngx-face-api-js --save

Giving proper path of testing image.
<img
  singleFace
  [with]="['expressions', 'landmarks']"
  [src]="imageSrc"
  width="300px"
/>

![Capture](https://user-images.githubusercontent.com/44866144/64847206-ef65b700-d627-11e9-80ef-2094dc0e07dc.PNG)

**If possible let me know how can i use this in Ionic app. Thank you :)**

**Comment by kamiazya** [comment]
@CodingApp 

I'm not very familiar with ionic, but I've compiled the steps for introducing it into the Angular project.

https://github.com/kamiazya/ngx-face-api-js/wiki/Manual-Installation

Try step 2 and later in this manual.

**Comment by kamiazya** [comment]
Please note that this project only supports Angular 7, so it does not support other versions of Angular.

**Comment by CodingApp** [comment]
@kamiazya Thank you so much for quick response, Ionic is an framework build on top of angular core. I will check the steps and respond soon.

**Comment by kamiazya** [comment]
This issue is closed because it is likely not a problem with this project.

If you have any questions about installation, I will continue to answer on this issue.

**Comment by CodingApp** [comment]
Can you explain this thing for me modelsUrl: 'path/to/face-api.js/weights' 
All package files should go in node_modules after installation, from where should i map the path in this. Thanks

**Comment by kamiazya** [comment]
@CodingApp 
ngx-face-api-js uses [face-api.js](https://github.com/justadudewhohacks/face-api.js) internally.

modelUrl needs to specify the path to load the learned model for face recognition in the face-api.js specification.

There are two ways to prepare a model.

- Download the following file and host it with your image files in your ionic project. https://github.com/justadudewhohacks/face-api.js/tree/master/weights
- Use a file hosted on raw.githubusercontent.com. 

It is recommended to specify 'https://raw.githubusercontent.com/justadudewhohacks/face-api.js/master/weights' for modelUrl because the second method is simple.

Thanks

**Comment by kamiazya** [comment]
Since there was no explanation about modelUrl, I added it to Wiki!

https://github.com/kamiazya/ngx-face-api-js/wiki/Manual-Installation#whats-modelurl

Thanks

**Comment by CodingApp** [comment]
**@kamiazya** 

Thank you so much for adding this in docs :)
